package it.polimi.ingsw.enumerations;

public enum ErrorType {

    NOT_ENOUGH_PLAYERS,
    DECK_IS_EMPTY,
    INVALID_CARD_POSITION,
    NOT_YOUR_TURN,
    REQUIREMENTS_NOT_MET, UNSPECIFIED, INVALID_USERNAME, GAME_ALREADY_STARTED,
}
